const express = require('express')
const router = express.Router()
const userRouter = require('./userRouter')
const PostRouter = require('./userPostRouter')
const PostComment = require('./userPostCommentRouter')
const NoticeRoute = require('./noticePostRouter')
const NoticeCommentRoute = require('./noticeCommentRouter')
const MemberRoute = require('./memberRouter')
const AdminRoute = require('./adminRoute')
const DonationPost = require('./donationPostRouter')
const PaymentRoute = require('./paymentRoutes')
const LocationRoute = require('./locationRouter')

router.use('/payment',PaymentRoute)
router.use('/donationpost',DonationPost)
router.use('/member',MemberRoute)
router.use('/registration',userRouter)
router.use('/userPost',PostRouter)
router.use('/postcomment',PostComment)
router.use('/notice',NoticeRoute)
router.use('/noticecomment',NoticeCommentRoute)
router.use('/Admin',AdminRoute)
router.use('/locations', LocationRoute)
module.exports = router
