const express = require('express')
require('dotenv').config()
const cors = require('cors')
const connectDB =  require('./config/db')
const errorMiddleWare = require('./middleware/errorMIddleware')
const router = require('./routes/index')
const app = express()
connectDB()
app.use(express.json())
app.use(cors())
app.use(router)
app.use(errorMiddleWare)
app.listen(5000,()=>{
    console.log('server is running successfully')

})